# Made this when learning ansible, put on blog at on http://blog.rackspace.com/how-to-deploy-ansible-accessible-explanation/
# Yes I know there is a module for making virtual environments.
---
- hosts: webservers
  sudo: yes

  vars:
    app_name: PleaseDeployMe
    repo_url: https://github.com/username/repo_name.git
    repo_remote: origin
    repo_version: master
    webapps_dir: /deployed  
    virtualenv_root: /deployed/PleaseDeployMe/mac
  tasks:
    
    - name: git pull project
      git: repo={{repo_url}} dest={{webapps_dir}}/{{app_name}} version=master
     
      notify:
        - restart app
    
    - name: install things
      pip: name=virtualenv
    
    - name: create virtualenv
      command: virtualenv /deployed/PleaseDeployMe/venv

    - name: activate virtualenv
      command: /bin/bash /deployed/PleaseDeployMe/venv/bin/activate

    - pip: requirements=/deployed/{{app_name}}/requirements.txt virtualenv=/deployed/{{app_name}}/mac

    - name: run supervisord
      command: "supervisord -c /deployed/PleaseDeployMe/supervisord.conf"
    
    - name: begin flask app
      supervisorctl: name=flask_app state=started


  handlers:
    - name: restart app
      supervisorctl: name={{app_name}} state=restarted

